// /*
//  * TVM Issue #10210 — Parallel Reduction Axis WAW Race
//  *
//  * Manually written to model the buggy TIR pattern.
//  *
//  * Bug: TVM's parallel() on reduction axis k launches 64 CPU threads
//  * all writing to the same accumulator C[i*64+j] without synchronisation.
//  *
//  * Modelled here as a CUDA kernel to enable GPUVerify analysis.
//  * In reality this runs on CPU OpenMP threads — no CUDA kernel is generated.
//  *
//  * Block: 64 threads (one per k iteration)
//  * Grid:  1 block
//  */

// #include <cuda.h>

// __global__ __launch_bounds__(64) void parallel_reduction_buggy(
//     float* C,
//     const float* A,
//     const float* B)
// {
//     int k = threadIdx.x;  // 64 threads, one per k
//     int i = 0, j = 0;

//     /* BUG: all 64 threads read and write C[i*64+j] = C[0]
//      * simultaneously with no atomic or __syncthreads()
//      * Thread 0:  C[0] = C[0] + A[0]*B[0]
//      * Thread 1:  C[0] = C[0] + A[1]*B[64]   <- reads same stale C[0]
//      * ...
//      * Last writer wins -> 63 updates lost -> wrong result */
//     C[i*64+j] = C[i*64+j] + A[i*64+k] * B[k*64+j];
// }


/*
 * TVM Issue #10210 — Tree reduction with shared memory is buggy
 * when threadIdx.y is present.
 *
 * This is the ACTUAL buggy CUDA kernel generated by TVM as shown
 * in the GitHub issue — not a manually written model.
 *
 * Bug: TVM assumes the reduction fits within a single warp when
 * blockDim.x=26 (NOT a multiple of warp size 32). It skips
 * __syncthreads() between reduction steps inside if(threadIdx.x < 8).
 * Because threadIdx.y is also active and threads span multiple warps,
 * __syncthreads() IS required between each step.
 *
 * Block: 26 x 16 x 1 = 416 threads
 * Grid:  1 block
 */

#include <cuda.h>

__global__ void default_function_kernel0(
    float* __restrict__ A,
    float* __restrict__ B)
{
    __shared__ float red_buf0[416];

    __syncthreads();

    /* Load input into shared memory */
    ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] =
        A[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))];

    __syncthreads();

    /* Reduction step 1: stride 16 */
    if (((int)threadIdx.x) < 10) {
        ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] =
            (((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] +
             ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x) + 16)]);
    }

    __syncthreads();

    /* BUG: Missing __syncthreads() between reduction steps below!
     * TVM assumed this fits in one warp (warp = 32 threads)
     * but blockDim.x = 26 which is NOT a multiple of 32.
     * With threadIdx.y active, threads span multiple warps.
     * Each step below needs __syncthreads() but TVM did not insert them. */
    if (((int)threadIdx.x) < 8) {
        /* Step 2: stride 8 */
        ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] =
            (((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] +
             ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x) + 8)]);
        /* MISSING __syncthreads() here! */

        /* Step 3: stride 4 */
        ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] =
            (((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] +
             ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x) + 4)]);
        /* MISSING __syncthreads() here! */

        /* Step 4: stride 2 */
        ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] =
            (((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] +
             ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x) + 2)]);
        /* MISSING __syncthreads() here! */

        /* Step 5: stride 1 */
        ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] =
            (((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x))] +
             ((volatile float*)red_buf0)[(((int)threadIdx.y) * 26 + ((int)threadIdx.x) + 1)]);
    }

    __syncthreads();

    /* Write result */
    B[(((int)threadIdx.y))] =
        ((volatile float*)red_buf0)[((((int)threadIdx.y) * 26))];
}